// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_api.Models;

#nullable disable

namespace quiz_api.Migrations
{
  [DbContext(typeof(QuizDbContext))]
  [Migration("20230611015123_InitialDb")]
  partial class InitialDb
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.16")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

      modelBuilder.Entity("quiz_api.Models.Question", b =>
          {
            b.Property<int>("QuestionId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

            b.Property<int>("Answer")
                      .HasColumnType("int");

            b.Property<string>("Option1")
                      .HasColumnType("nvarchar(50)");

            b.Property<string>("Option2")
                      .HasColumnType("nvarchar(50)");

            b.Property<string>("Option3")
                      .HasColumnType("nvarchar(50)");

            b.Property<string>("Option4")
                      .HasColumnType("nvarchar(50)");

            b.Property<string>("QuestionInWords")
                      .HasColumnType("nvarchar(250)");

            b.HasKey("QuestionId");

            b.ToTable("Questions");
          });
#pragma warning restore 612, 618
    }
  }
}
